name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: public

jobs:
  # Please do not rename this job
  build-project:
    name: build MyWebsiteLeo
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install # Installiere die Abhängigkeiten

      - name: Build Node assets
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
        run: npm run build # Führe den Build-Befehl aus

      # Please do not touch the following action
      - name: Store deployment content
  uses: ionos-deploy-now/artifact-action@v1
  with:
    api-key: ${{ secrets.IONOS_API_KEY }}
    service-host: api-eu.ionos.space
    project-id: 57a5ce729edc75f1649f3051f3b8d6a01d78c181
    branch-id: ${{ inputs.branch-id }}
    version: ${{ github.sha }}
    folder: ${{ env.DEPLOYMENT_FOLDER }}
    config-file: .deploy-now/Portfolio/config.yaml
    action: upload
